hello-world (UjwalaHS/simple-java-maven-app/.github/actions/print_env_var/action.yml)
|   |__ .github
|       └── workflows
|           └── my-first-workflow.yml
|       └── actions
|           |__ hello-world-action
|               └── action.yml
